GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/${id}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Ricardo"
}

###
PUT http://localhost:3000/api/users/${id}
Content-Type: application/json

{
  "name": "Tommy"
}

###
DELETE http://localhost:3000/api/users/${id}
